# Generated by Django 5.1.4 on 2024-12-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile.html',
            old_name='user',
            new_name='custom_user',
        ),
    ]
